name: appaviao
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  sqflite_common_ffi:


dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  sqflite: ^2.0.0+3
  mysql1: ^0.19.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/dogdino.png
    - assets/images/aviao.png
    - assets/images/aviaocriartela.png
    - assets/images/aviaosfundo.png
    - assets/images/logo_airtravel.png

